tasks:
  - init: |
      docker-compose pull
  - name: Start syncing the testnet with cardano-node
    command: docker-compose up
  - name: Client where we will write queries.
    command: docker-compose run cardano cli query tip --testnet-magic 1097911063
    openMode: tab-after


ports:
  - port: 5000
    onOpen: ignore
  - port: 5601
    onOpen: open-browser
  - port: 9200
    onOpen: open-preview
  - port: 9300
    onOpen: ignore
  - port: 9600
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
