version: '3'

services:
  cardano-node:
    image: inputoutput/cardano-node
    volumes:
     - ./cardano-testnet-1097911063/_data:/data
     - node-ipc:/ipc
    environment:
      - NETWORK=testnet

  cardano-cli:
    image: inputoutput/cardano-node
    volumes:
      - node-ipc:/ipc:ro
    tty: true
    stdin_open: true
    environment:
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
    command: cli
    profiles:
      - cardano-cli
    depends_on:
      - cardano-node

  plutus-starter-kit:
    image: inputoutput/plutus-starter-devcontainer

volumes:
  cardon_node_data:
    external: true
  node-ipc:
    external: true
